#---- 1. Site config ----

site_name: MaterialX
site_url: https://jaywhj.github.io/mkdocs-materialx/
site_author: Aaron Wang
site_description: >-
  Born for documents, yet beyond documents. 
  Accessible to everyone, extremely easy to use. 
  Modern, lightweight, customizable, responsive.

repo_name: jaywhj/mkdocs-materialx
repo_url: https://github.com/jaywhj/mkdocs-materialx

copyright: Copyright &copy; 2016 - 2026 Aaron Wang

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaywhj
      name: GitHub
    - icon: material/email
      link: mailto:junewhj@qq.com
      name: Email
    - icon: fontawesome/brands/discord
      link: https://discord.gg/cvTfge4AUy
      name: Discord


#---- 2. Theme ----

theme:
  name: materialx
  custom_dir: material/overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.footnote.tooltips
    - content.tooltips

    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    # - navigation.expand
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.footer

    - search.highlight
    - search.share
    - search.suggest

    - toc.follow
    # - toc.integrate

  # topbar_style: primary   # glass primary accent
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font: false
  favicon: assets/favicon.png
  icon:
    logo: logo
    annotation: material/plus-circle-outline


#---- 3. Plugins & Hooks ----

plugins:
  # - blog
  # - tags
  - offline
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true

  - document-dates:
      type: timeago
      locale: en
      exclude: ['index.md', 'license.md', '*/index.md', 'blog/*']

  - glightbox

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py


#---- 4. Extensions ----

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      toc_depth: 4
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
      # smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


#---- 5. Page tree ----

# use_directory_urls: false
# exclude_docs: |
#   /drafts/
# not_in_nav: |
#   /tutorials/**/*.md

nav:
  - Home: index.md
  - Get started:
    - Differences: differences.md
    - Installation: installation.md
    - Create your site: creating-your-site.md
    - Publish your site: publishing-your-site.md
    - Customization: customization.md
  - Setup:
    - setup/index.md
    - Logo and icons: setup/changing-the-logo-and-icons.md
    - Colors: setup/changing-the-colors.md
    - Fonts: setup/changing-the-fonts.md
    - Language: setup/changing-the-language.md
    - Navigation: setup/setting-up-navigation.md
    - Dates & authors: setup/adding-document-dates-authors.md
    - Recently updated: setup/adding-recent-updates-module.md
    - Repository: setup/adding-a-git-repository.md
    - Site search: setup/setting-up-site-search.md
    - Site analytics: setup/setting-up-site-analytics.md
    - Social cards: setup/setting-up-social-cards.md
    - Tags: setup/setting-up-tags.md
    - Header: setup/setting-up-the-header.md
    - Footer: setup/setting-up-the-footer.md
    - Comment system: setup/adding-a-comment-system.md
    - Versioning: setup/setting-up-versioning.md
    - Data privacy: setup/ensuring-data-privacy.md
    - Blog: setup/setting-up-a-blog.md
    # - Building an optimized site: setup/building-an-optimized-site.md
    # - Building for offline usage: setup/building-for-offline-usage.md
    - Extensions:
      - setup/extensions/index.md
      - Markdown: setup/extensions/python-markdown.md
      - Markdown Extensions: setup/extensions/python-markdown-extensions.md
  - Plugins:
    - plugins/index.md
    - Tags: plugins/tags.md
    - Blog: plugins/blog.md
    - Meta: plugins/meta.md
    - Search: plugins/search.md
    - Social: plugins/social.md
    - Offline: plugins/offline.md
    - Optimize: plugins/optimize.md
    - Privacy: plugins/privacy.md
    - Group: plugins/group.md
    - Info: plugins/info.md
    # - Projects: plugins/projects.md
    # - Typeset: plugins/typeset.md
    - Requirements:
      - Image processing: plugins/requirements/image-processing.md
      - Caching: plugins/requirements/caching.md
  - Authoring:
    - reference/index.md
    - Admonitions: reference/admonitions.md
    - Annotations: reference/annotations.md
    - Buttons: reference/buttons.md
    - Code blocks: reference/code-blocks.md
    - Content tabs: reference/content-tabs.md
    - Data tables: reference/data-tables.md
    - Diagrams: reference/diagrams.md
    - Footnotes: reference/footnotes.md
    - Formatting: reference/formatting.md
    - Grids: reference/grids.md
    - Icons, Emojis: reference/icons-emojis.md
    - Images: reference/images.md
    - Lists: reference/lists.md
    - Math: reference/math.md
    - Tooltips: reference/tooltips.md
  # - Insiders:
  #   - insiders/index.md
  #   - Getting started: insiders/getting-started.md
  #   - Changelog:
  #     - insiders/changelog/index.md
  #     - How to upgrade: insiders/upgrade.md
  - Community:
    - Contributing:
      - contributing/index.md
      - Reporting a bug: contributing/reporting-a-bug.md
      - Reporting a docs issue: contributing/reporting-a-docs-issue.md
      - Requesting a change: contributing/requesting-a-change.md
      - Adding translations: contributing/adding-translations.md
      - Making a pull request: contributing/making-a-pull-request.md
      - Asking a question: https://github.com/jaywhj/mkdocs-materialx/discussions
    - Guides:
      - Creating a reproduction: guides/creating-a-reproduction.md
  - Tutorials:
    # - tutorials/index.md
    - "Blogs":
      - tutorials/blogs/basic.md
      - tutorials/blogs/navigation.md
      - tutorials/blogs/engage.md
    - "Social cards":
      - tutorials/social/basic.md
      - tutorials/social/custom.md
  # - Blog:
    # - blog/index.md

  - System:
    - Conventions: conventions.md
    - Browser support: browser-support.md
    # - Philosophy: philosophy.md
    # - Alternatives: alternatives.md
    - License: license.md
    - Changelog:
      - changelog/index.md
      - How to upgrade: upgrade.md